name: Build Pinnacle (Manual Deps)

on:
  workflow_dispatch:
    inputs:
      rootful:
        description: "Build for Rootful"
        type: boolean
        default: false
      rootless:
        description: "Build for Rootless"
        type: boolean
        default: true
      roothide:
        description: "Build for Roothide"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Pinnacle
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: roothide/theos
          ref: c824e3569032551f1ce8c6eab6c2611bbf4f7bad
          path: theos
          submodules: recursive

      - name: Download iOS SDK
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS14.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Tweak
        id: build_package
        run: |
          cd ${{ github.workspace }}/main

          if [ "${{ inputs.rootful }}" == "true" ]; then
            echo "Building Rootful..."
            make clean package FINALPACKAGE=1
          fi

          if [ "${{ inputs.rootless }}" == "true" ]; then
            echo "Building Rootless..."
            make clean package ROOTLESS=1 FINALPACKAGE=1
          fi

          if [ "${{ inputs.roothide }}" == "true" ]; then
            echo "Building Roothide..."
            make clean package ROOTHIDE=1 FINALPACKAGE=1
          fi
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.run_number }}"
          name: Pinnacle v${{ github.run_number }}
          files: main/packages/*.deb
          draft: false
